#Default Config
#gameVariables: 
#  minPercentPlayers: 50	//The percentage of a full lobby, before players in queue are teleported and before a game will start. 
#  allowSpectating: false   //if SpectatorPlus is installed, setting this to true will put players in spectator mode when they lose all their lives. 
#  usingEconomy: false      //if set to true, the amounts listed in pointsPerKill and pointsPerWin will be added to players balance for kills and wins. pointsLostPerDeath will be subtracted from balance on death.
#  noFallDamage: true		//if set to true, players will not be damaged when they fall in game. 
#  pointsPerKill: 2			//number of score points players receive per kill or lose per death.
#  pointsPerWin: 10			//number of score points players receive per win.
#  pointsLostPerDeath: 1	//number of score points players lose per death.
#  pointsLostPerLeave: 1	//number of score points players lose if they leave a match mid-game.
#  maxMapSize: 400			//maximum square size of the game map. The map should be centered around 0, 0, 0
#  mapsPerWorld: 100		//The number of maps that will be generated per world
#  maxNumberOfGames: -1		//the maximum number of games that the plugin will allow at one time. -1 means no limit. If a player tries to join a game and the limit is already met, they are added to a queue and will join the next available game.  
#  kitsEnabled: true		//set to false to disable kits.
#  shopsEnabled: true       //when set to true, players can use the swr shop command to buy items in game. Shop is setup in the shop.yml.
#  timeAfterGame: 10		//the amount of time after the game ends before all players are teleported to spawn. 
#  statsCommandCooldown: 60	//the amount of cooldown before a player can reuse the stats command.
#  directToLobby: true		//when enabled, players are sent directly to the lobby when joining a game. If disabled, players are placed in a queue and will be sent to the lobby when the minimum number of players needed is met. 
#  directToCages: false		//when enabled, a random map will be chosen and players will be teleported directly to the cages. 
#  giveSpectateItem: true	//when this is enabled, any player who has the spectate permission will be given a special item that allows them to spectate other games when they join.
#  addScorePrefix: true		//when enabled, a players score will be put in front of any message they send. 
#  opChestsEnabled: false	//when enabled, players with the swr.opchest permission will be given a voting tool in lobby. They can vote on whether the match will use OP chests as defined in the opchest.yml file. 
#spawn:						//use setspawn command to set a spawn point where people are teleported when leaving a game. If no spawn is set, they will be teleported to their previous location.
#commandWhiteList: 			//commands placed under the whitelist can be used by players ingame. 
# - '/swr quit'
# - '/swr kit'
# - '/swr shop'
# - '/swr'
#sqldatabase:
#  enabled: false			//enable to store stats in a SQL database
#  saveInterval: 5			//time in minutes between SQL database updates - how often the plugin sends player stats to the database
#  hostname: localhost		//hostname of the SQL database
#  port: 3306				//port of the SQL database
#  database: database		//database being used
#  username: username      	//username for login to the SQL database
#  password: password		//password for login to the SQL database
#resaveDefaultMaps: false	//When set to true the plugin will reload the maps that came with the plugin.
#bungeeMode:
#  enabled: false			//When enabled, the plugin will work with the SkyWarsReloaded bungeeMode plugin. 
#  name: test				//The name that will be given to games on this server - this will be required when setting up signs on the lobby server (It must be unique for each server).
#  lobbyServer: lobby		//The name of the server (as found in bungeecord) where players will be sent when the game ends. 

signJoinMode: false
gameVariables: 
  minPercentPlayers: 50
  allowSpectating: true
  useExternalEconomy: false
  noFallDamage: true
  noFallDamageLobby: false
  pointsPerKill: 2
  pointsLostPerDeath: 1
  pointsLostPerLeave: 1
  pointsPerWin: 10
  vipMultiplier: 2
  preGameTimer: 20
  maxMapSize: 200
  maxNumberOfGames: -1
  kitsEnabled: true
  shopsEnabled: true
  timeAfterGame: 10
  statsCommandCooldown: 60
  addScorePrefix: true
  useExternalChat: false
  opChestsEnabled: true
  timeVoteEnabled: true
  jumpVoteEnabled: true
  colorGlassEnabled: true
  lobbyMenuEnabled: true
  purchaseColorGlassEnabled: true
  purchasePermanentKitsEnabled: true
  highJumpValue: 2
  superJumpValue: 4
  godJumpValue: 8
  spectateShopEnabled: true
  enableLogFilter: true
  lobbyScoreBoardEnabled: false
  disableWinBroadcast: false
  clearInventoryOnJoin: false
  clearXPOnJoin: false
  clearPotionEffectsOnJoin: false
  signJoinMaterial: wool
gameItems:
  giveSpectateItem: true
  spectateItemSlot: 0
  giveLobbyMenuItem: true
  lobbyMenuItemSlot: 4
  giveJoinItem: true
  joinItemSlot: 8
  lobbyMenuItem: eye_of_ender 1 luck:1
  spectateItem: compass 1 luck:1
  joinItem: daylight_detector 1 luck:1
  exitGameItem: iron_door 1 luck:1
  kitMenuItem: storage_minecart 1 luck:1
  kitPermMenuItem: storage_minecart 1
  specStoreItem: anvil 1 luck:1
  opChestMenuItem: diamond 1
  timeMenuItem: watch 1
  jumpMenuItem: diamond_boots 1
  optionsItem: cake 1 luck:1
  glassMenuItem: stained_glass 1
gameSounds:
  playerJoinLobby: SLIME_WALK2
  playerLeaveLobby: SLIME_ATTACK
  playerDeath: AMBIENCE_THUNDER
  playerWin: FIREWORK_LARGE_BLAST
  opChestVote: CHEST_OPEN
  timeVote: FUSE
spawn:
commandWhitelist:
- '/swr quit'
- '/swr kit'
- '/swr shop'
- '/swr start'
- '/swr'
- '/g'
spectatorWhitelist:
- '/swr quit'
sqldatabase:
  enabled: false
  saveInterval: 5
  hostname: localhost
  port: 3306
  database: database
  username: username
  password: password
resaveDefaultMaps: true
bungeeMode:
  enabled: false
  bungeeServerName: skywars
  lobbyServer: lobby