#Default Config
#gameSettings:
#  signJoinMode: false		//When enabled, players can join games through signs.
#  signJoinMaterial: wool	//This is the material that will show behind or under sign join signs. It can be set to wool, clay, glass or none.
#  pressurePlateJoin: true	//When enabled, players can join games by stepping on stone pressure plates.
#  allowSpectating: true	//Setting this to true will put players in spectator mode when they lose all their lives. 
#  enableLogFilter: true	//Enabling this filter allows SWR to remove the log spam created when worlds are loaded. 
#  useExternalEconomy: false	//if set to true, SWR with use your external economy plugin for shops and kits, as well as adding points for wins, kills, etc.  
#  disableWinBroadcast: false	//if set to true, only the players in the arena will see the winner message.
#  noFallDamage: true			//if set to true, players will not receive fall damage while in game. 
#  noFallDamageLobby: false		//if set to true, players will not recieve fall damage in the lobby world. 
#  minPercentPlayers: 50	//The percentage of a full lobby, before players in queue are teleported and before a game will start.
#  preGameTimer: 20			//The countdown time before the game starts once the minimum number of players are in the game.
#  resetPreGameTimerOnJoin: true	//If set to true, the pregame timer will reset whenver a new player joins a game.
#  resetPreGameTimerThreshold: 80	//This is the threshold based on the percentage of players in a game. If the number of players in the game is higher than the threshold, the timer will not restart. 
#  timeAfterGame: 10	//This is the amount of time after the end of a game, before the game shutsdown/restarts.
#  maxMapSize: 200		//This is the maximum square size of the map. 
#  maxNumberOfGames: -1 	//This is the maximum number of games possible on the server. If set to -1, it is unlimited. 
#  maxGameLength: -1		//Sets the maximum length of a game in minutes. 
#  playerNameScoreboard: false 	//When enabled, the in game scoreboard will show player names instead of Warriors Remaining.
#  lobbyScoreBoardEnabled: false //When enable, a scoreboard showing player stats will be shown to players in the Lobby World.
#  statsCommandCooldown: 60		//The amount of time a player has to wait to use the stats command again.
#  clearInventoryOnJoin: false	//When set to true, a players inventory is cleared whenever they join the server.
#  clearXPOnJoin: false		//When set to true, a players xp is cleared whenever they join the server.
#  clearPotionEffectsOnJoin: false  //When set to true, a players potions effects are cleared whenever they join the server.
#  addScorePrefix: true		//When set to true, a score prefix is added to player chat. 
#  useExternalChat: false	//When set to true, the plugin will use the external chat plugin.
#points:
#  pointsPerKill: 2		//number of points awarded per kill.
#  pointsLostPerDeath: 1	//number of points lost per death.
#  pointsLostPerLeave: 1	//number of points lost per leave.
#  pointsPerWin: 10		//number of points awarded per win.
#  vipMultiplier: 2		//The multiplier value added to points awarded to players with the swr.vip permission.
#gameOptions:
#  kitsEnabled: true	//enables kits
#  shopsEnabled: true	//enables in game shop
#  spectateShopEnabled: true	//enabled spectator shop
#  opChestsEnabled: true	//enables OP Chest voting
#  timeVoteEnabled: true	//enables Time voting
#  jumpVoteEnabled: true	//enables Jump voting
#  highJumpValue: 2			//sets the jump boost value of high jump.
#  superJumpValue: 4		//sets the jump boost value of super jump.
#  godJumpValue: 8			/sets the jump boost value of god jump.
#  weatherVoteEnabled: true		//enables weather voting.
#  lightningStrikeChance: 5		//chance that lightning will hit a random player during thunderstorm weather.
#  colorGlassEnabled: true		//enables players to change their glass colors (with permissions)
#  particlesEnabled: true		//enables players to change their particle effects (with permissions)
#  trailEffectsEnabled: true	//enables players to change their trail effects (with permissions)
#  lobbyMenuEnabled: true		//enables the lobby menu 
#  optionsMenuEnabled: true		//enables the in game options menu
#  purchaseColorGlassEnabled: true	//enables the Color Glass shop
#  purchaseParticlesEnabled: true	//enables the Particle Effects shop
#  purchaseTrailEffectsEnabled: true	//enables the Trail Effects shop
#  purchasePermanentKitsEnabled: true	//enables the Permanent Kit shop
#  showKitItemsandPotionEffects: true   //when enabled, the items and potion effects are displayed in the kit info.
#  doubleChestAlwaysOP: true		//when enabled, double chests are treated as OP chests (so you can have OP chests in the center of the map if you want)
#lobbyGuard:
#  enabled: false	//If enabled the items below will be enforced if set to true.
#  hungerDisabled: true  //Players will not lose hunger in lobby.
#  damageDisabled: true  //Player will not take damage in the lobby (Void damage will still be allowed).
#  pvpDisabled: true     //PVP will be disabled in the lobby.
#  playerBuildDisabled: true  //Players will not be able to build or break blocks in the lobby. 
#  playerInteractDisabled: true  //Players will not be able to interact with blocks/items/picture frames/etc in the lobby.
#  weatherDisabled: true //When enabled the weather will always be clear in the lobby world.
#  daylightCycleDisabled: true  //When enabled the time will always be Noon in the lobby world. 
#spawn:						//use setspawn command to set a spawn point where people are teleported when leaving a game. This must be set before any game can be created.
#commandWhiteList: 			//commands placed under the whitelist can be used by players ingame. 
# - '/swr quit'
# - '/swr kit'
# - '/swr shop'
# - '/swr'
#sqldatabase:
#  enabled: false			//enable to store stats in a SQL database
#  saveInterval: 5			//time in minutes between SQL database updates - how often the plugin sends player stats to the database
#  hostname: localhost		//hostname of the SQL database
#  port: 3306				//port of the SQL database
#  database: database		//database being used
#  username: username      	//username for login to the SQL database
#  password: password		//password for login to the SQL database
#resaveDefaultMaps: false	//When set to true the plugin will reload the maps that came with the plugin.
#bungeeMode:
#  enabled: false			//When enabled, the plugin will work with the SkyWarsReloaded bungeeMode plugin. 
#  bungeeServerName: test	//The bungee cord name of the SkyWars server.
#  lobbyServer: lobby		//The name of the server (as found in bungeecord) where players will be sent when the game ends. 
gameSettings:
  signJoinMode: false
  signJoinMaterial: wool
  pressurePlateJoin: true
  allowSpectating: true
  enableLogFilter: true
  useExternalEconomy: false  
  disableWinBroadcast: false
  noFallDamage: true
  minPercentPlayers: 50
  preGameTimer: 20
  resetPreGameTimerOnJoin: true
  resetPreGameTimerThreshold: 80
  timeAfterGame: 10
  maxMapSize: 200
  maxNumberOfGames: -1
  maxGameLength: -1
  playerNameScoreboard: false 
  lobbyScoreBoardEnabled: false
  statsCommandCooldown: 60
  clearInventoryOnJoin: false
  clearXPOnJoin: false
  clearPotionEffectsOnJoin: false
  sendPlayersToSpawnOnJoin: false
  addScorePrefix: true
  useExternalChat: false
points:
  pointsPerKill: 2
  pointsLostPerDeath: 1
  pointsLostPerLeave: 1
  pointsPerWin: 10
  vipMultiplier: 2
gameOptions:
  kitsEnabled: true
  shopsEnabled: true
  spectateShopEnabled: true
  opChestsEnabled: true
  timeVoteEnabled: true
  jumpVoteEnabled: true
  highJumpValue: 2
  superJumpValue: 4
  godJumpValue: 8
  weatherVoteEnabled: true
  lightningStrikeChance: 5
  colorGlassEnabled: true
  particlesEnabled: true
  trailEffectsEnabled: true
  lobbyMenuEnabled: true
  optionsMenuEnabled: true
  purchaseColorGlassEnabled: true
  purchaseParticlesEnabled: true
  purchaseTrailEffectsEnabled: true
  purchasePermanentKitsEnabled: true
  showKitItemsandPotionEffects: true
  doubleChestAlwaysOP: true
gameItems:
  giveSpectateItem: true
  spectateItemSlot: 0
  giveLobbyMenuItem: true
  lobbyMenuItemSlot: 4
  giveJoinItem: true
  joinItemSlot: 8
  lobbyMenuItem: eye_of_ender 1 luck:1
  spectateItem: compass 1 luck:1
  joinItem: daylight_detector 1 luck:1
  exitGameItem: iron_door 1 luck:1
  exitItemSlot: 8
  kitMenuItem: storage_minecart 1 luck:1
  kitMenuItemSlot: 0
  kitPermMenuItem: storage_minecart 1
  kitPermMenuItemSlot: 2 
  specStoreItem: anvil 1 luck:1
  specStoreItemSlot: 4
  opChestMenuItem: diamond 1
  opChestOptionMenuSlot: 3
  timeMenuItem: watch 1
  timeOptionMenuSlot: 5
  weatherMenuItem: glowstone 1
  weatherOptionMenuSlot: 7
  jumpMenuItem: diamond_boots 1
  jumpOptionMenuSlot: 1
  particleMenuItem: pumpkin_seeds 1
  particleLobbyMenuSlot: 20
  particleOptionsMenuSlot: 22
  trailEffectMenuItem: arrow 1
  trailEffectLobbyMenuSlot: 24
  trailEffectOptionsMenuSlot: 24
  optionsItem: cake 1 luck:1
  optionsItemSlot: 4
  glassMenuItem: stained_glass 1
  glassLobbyMenuSlot: 6
  glassOptionsMenuSlot: 20
gameSounds:
  playerJoinLobby: SLIME_WALK2
  playerLeaveLobby: SLIME_ATTACK
  playerDeath: AMBIENCE_THUNDER
  playerWin: FIREWORK_LARGE_BLAST
  opChestVote: CHEST_OPEN
  timeVote: FUSE
  weatherVote: SPLASH
  jumpVote: MAGMACUBE_JUMP
lobbyGuard:
  enabled: false
  hungerDisabled: true
  fallDamageDisabled: true
  damageDisabled: true
  pvpDisabled: true
  playerBuildDisabled: true
  playerInteractDisabled: true
  weatherDisabled: true
  daylightCycleDisabled: true
spawn:
commandWhitelist:
- '/swr quit'
- '/swr kit'
- '/swr shop'
- '/swr start'
- '/swr'
- '/g'
spectatorWhitelist:
- '/swr quit'
- '/swr shop'
sqldatabase:
  enabled: false
  saveInterval: 30
  hostname: localhost
  port: 3306
  database: database
  username: username
  password: password
resaveDefaultMaps: true
bungeeMode:
  enabled: false
  bungeeServerName: skywars
  lobbyServer: lobby